create table if not exists public.user_learning_state (
  user_id uuid primary key references auth.users on delete cascade,
  progress jsonb not null default '{}'::jsonb,
  language text not null default 'zh' check (language in ('zh', 'en')),
  updated_at timestamptz not null default now()
);

alter table public.user_learning_state enable row level security;

drop policy if exists "Users can read their own learning state" on public.user_learning_state;
create policy "Users can read their own learning state"
  on public.user_learning_state
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own learning state" on public.user_learning_state;
create policy "Users can insert their own learning state"
  on public.user_learning_state
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own learning state" on public.user_learning_state;
create policy "Users can update their own learning state"
  on public.user_learning_state
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.mock_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  source_label text not null,
  score integer not null,
  correct_count integer not null,
  total_count integer not null,
  unanswered_count integer not null default 0,
  elapsed_ms integer not null,
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.mock_attempts enable row level security;

drop policy if exists "Users can read their own mock attempts" on public.mock_attempts;
create policy "Users can read their own mock attempts"
  on public.mock_attempts
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own mock attempts" on public.mock_attempts;
create policy "Users can insert their own mock attempts"
  on public.mock_attempts
  for insert
  with check (auth.uid() = user_id);

create table if not exists public.site_comments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete set null,
  display_name text not null check (char_length(btrim(display_name)) between 1 and 40),
  rating integer not null check (rating between 1 and 5),
  comment text not null check (char_length(btrim(comment)) between 1 and 500),
  is_public boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.site_comments enable row level security;

drop policy if exists "Anyone can read public site comments" on public.site_comments;
create policy "Anyone can read public site comments"
  on public.site_comments
  for select
  using (is_public = true);

drop policy if exists "Anyone can insert public site comments" on public.site_comments;
create policy "Anyone can insert public site comments"
  on public.site_comments
  for insert
  with check (
    is_public = true
    and rating between 1 and 5
    and char_length(btrim(display_name)) between 1 and 40
    and char_length(btrim(comment)) between 1 and 500
    and (user_id is null or auth.uid() = user_id)
  );

create index if not exists site_comments_public_created_idx
  on public.site_comments (is_public, created_at desc);
